### ISSUE TITLE
Feature: Expose the debugger data with a service

### ISSUE THREAD

**Issue by J3m5** [radenkovic/feathers-debugger#1]
A good start for the debugger service would be to use [feathers-nedb](https://github.com/feathersjs-ecosystem/feathers-nedb) or [feathers-lowdb](https://github.com/lwhiteley/feathers-lowdb) as a database service adapter.

**Comment by radenkovic** [comment]
I need some information from Feathers maintainers how to implement the service, so it can be used with one line. That's the first thing I am pushing in next version!

**Comment by radenkovic** [comment]
@J3m5 
Check [this](https://github.com/radenkovic/feathers-debugger-service/tree/master/src) out: Thanks for the idea with `feathers-nedb`, integration was a breeze! I am waiting for Chrome to review the extension (1.2.0) and will post you here!

**Comment by J3m5** [comment]
That's great!
